# Deploy a certbot instance on a private network

- hosts: localhost

  vars_files:
    - globals.yml

  tasks:

  - name: Create network
    openstack.cloud.network:
      cloud: "{{ cloud_name }}"  # name of the cloud specified in clouds.yaml
      state: present
      name: private
      external: false
    register: network_details

  - name: Create subnet
    openstack.cloud.subnet:
      cloud: "{{ cloud_name }}"
      state: present
      network_name: "{{ network_details.network.id }}"
      name: "{{ subnet_name }}"
      cidr: "{{ subnet_cidr }}"
      dns_nameservers: "{{ dns_nameservers }}"
    register: subnet_details

  - name: Deploy a compute instance
    openstack.cloud.server:
      cloud: "{{ cloud_name }}"
      state: present
      name: "{{ instance_name }}"
      image: "{{ image_uuid }}"
      key_name: "{{ ssh_key }}"
      timeout: 200
      flavor: "{{ instance_flavor }}"
      auto_ip: no
      nics:
        - net-id: "{{ network_details.network.id }}"
