# Deploy a certbot instance on a private network
# Relies on /etc/openstack/clouds.yaml for auth

- hosts: localhost
  vars_files:
    - vars/globals.yml
  tasks:
  - name: Delete existing certbot compute instance
    openstack.cloud.server:
      cloud: "{{ cloud_name }}"
      name: "{{ instance_name }}"
      state: absent

  - name: Delete existing router
    openstack.cloud.router:
      cloud: "{{ cloud_name }}"
      state: absent
      name: "{{ router_name }}"

  - name: Delete existing subnet
    openstack.cloud.subnet:
      cloud: "{{ cloud_name }}"
      state: absent
      name: "{{ subnet_name }}"

  - name: grab images
    openstack.cloud.image_info:
    register: result

  - name: find ubuntu 22 image id
    set_fact:
      ubuntu_image_uuid: "{{ item.id }}"
    loop: "{{ result.images }}"
    when: "'Ubuntu 22' in item.name"

  - name: Add SSH key
    openstack.cloud.keypair:
      cloud: "{{ cloud_name }}"
      state: present
      name: "{{ ssh_key }}"
      public_key_file: "{{ ansible_user_dir }}/.ssh/id_rsa.pub"

  - name: Create network
    openstack.cloud.network:
      cloud: "{{ cloud_name }}"
      state: present
      name: "{{ private_network }}"
      external: false
    register: network_details

  - name: Create subnet
    openstack.cloud.subnet:
      cloud: "{{ cloud_name }}"
      state: present
      network_name: "{{ network_details.network.id }}"
      name: "{{ subnet_name }}"
      cidr: "{{ subnet_cidr }}"
      dns_nameservers: "{{ dns_nameservers }}"
    register: subnet_details

  - name: Create router
    openstack.cloud.router:
      cloud: "{{ cloud_name }}"
      state: present
      name: "{{ router_name }}"
      network: "{{ external_network }}"
      interfaces:
        - net: "{{ private_network }}"
          subnet: "{{ subnet_details.subnet.id }}"


  - name: Deploy a compute instance
    openstack.cloud.server:
      cloud: "{{ cloud_name }}"
      state: present
      name: "{{ instance_name }}"
      image: "{{ ubuntu_image_uuid }}"
      key_name: "{{ ssh_key }}"
      timeout: 200
      flavor: "{{ instance_flavor }}"
      auto_ip: no
      nics:
        - net-id: "{{ network_details.network.id }}"
      security_groups: "{{ instance_sec_groups }}"

  - name: Attach floating IP
    openstack.cloud.floating_ip:
      cloud: "{{ cloud_name }}"
      state: present
      network: "{{ external_network }}"
      server: "{{ instance_name }}"
      wait: true
      timeout: 180
    register: floating_ip
